- name: Playbook to create webserver
  hosts: all
  become: true
  tasks:
    - name: install package
      yum: 
        state: latest
        name: httpd

    - name: start httpd daemon
      service: 
        state: started
        name: httpd
        enabled: true

    - name: Deploy website
      copy:
       src: ./buzzed-html-templete
       dest: /var/www/html/